default_stages: [pre-commit]
ci:
  autoupdate_commit_msg: 'chore(deps): pre-commit.ci autoupdate'
  autoupdate_schedule: monthly
  autofix_commit_msg: 'style: pre-commit.ci fixes'
  skip:
    - nbqa-ruff
    - nbqa-pyupgrade
    - nbqa-pylint

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/luminartech/dev-tools
    rev: 0.7.0
    hooks:
      - id: check-snake-case
      - id: check-cpp-and-cu-unit-test-naming-pattern
      - id: check-non-existing-and-duplicate-excludes
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.21
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-shfmt
          - mdformat-config
          - mdformat-toc
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.6
    hooks:
      - id: markdown-link-check
        args: ["--quiet", "--config", ".md-link-config.json"]
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping=2, --sequence=4, --offset=2, --implicit_start, --preserve-quotes]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
  - repo: https://github.com/PyCQA/docformatter
    # Use tag > v1.7.5 if available
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear  # Not fully implemented by ruff
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.3
    hooks:
      - id: pylint
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
      - id: nbqa-pyupgrade
        args:
          - --py39-plus
      - id: nbqa-pylint
        args: [--rcfile=.pylintrc-nb.ini]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/crate-ci/typos
    rev: dictgen-v0.3.1
    hooks:
      - id: typos
        exclude_types:
          - cmake
